name: Node.js CI

on: [push, pull_request]

jobs:
  tests:
    name: Tests
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [10.x, 12.x, 14.x, 15.x]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout the source
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install the dependencies
      run: yarn install
    - name: Run the tests
      uses: GabrielBB/xvfb-action@v1
      with:
        run: yarn test
